#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest -v tests/* --junitxml=test-reports/report.xml

            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: 'waiter-caller'
                HEROKU_APP_NAME: '5414e02f-7e3c-4237-8c91-2c88e900e463'
                WAIT: 'true' # Optional.
